CREATE VIEW VIEW_USER_INFORMATION
AS SELECT U.USER_ID,
  U.FIRST_NAME,
  U.LAST_NAME,
  U.YEAR_OF_BIRTH,
  U.MONTH_OF_BIRTH,
  U.DAY_OF_BIRTH,
  U.GENDER,
(SELECT CITY_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (CC.CITY_ID = C.CITY_ID)
) AS CURRENT_CITY,
(SELECT STATE_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (CC.CITY_ID = C.CITY_ID)
) AS CURRENT_STATE,
(SELECT COUNTRY_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (CC.CITY_ID = C.CITY_ID)
) AS CURRENT_COUNTRY,
(SELECT CITY_NAME
	FROM CITIES
	WHERE (U.USER_ID = HC.USER_ID) AND (HC.CITY_ID = C.CITY_ID)
) AS HOMETOWN_CITY,
(SELECT STATE_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (HC.CITY_ID = C.CITY_ID)
) AS HOMETOWN_STATE,
(SELECT COUNTRY_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (HC.CITY_ID = C.CITY_ID)
) AS HOMETOWN_COUNTRY,
  E.INSTITUTION,
  E.PROGRAM_YEAR,
  P.CONCENTRATION,
  P.DEGREE
  FROM USERS U,
  CITIES C,
  USER_CURRENT_CITIES CC,
  USER_HOMETOWN_CITIES HC,
  PROGRAMS P,
  EDUCATION E
WHERE (E.USER_ID = U.USER_ID) AND
  (P.PROGRAM_ID = E.PROGRAM_ID);

CREATE VIEW VIEW_ARE_FRIENDS
AS SELECT USER1_ID,
USER2_ID
FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION
AS SELECT A.ALBUM_ID,
  A.ALBUM_OWNER_ID,
  A.COVER_PHOTO_ID,
  A.ALBUM_NAME,
  A.ALBUM_CREATED_TIME,
  A.ALBUM_MODIFIED_TIME,
  A.ALBUM_LINK,
  A.ALBUM_VISIBILITY,
  P.PHOTO_ID,
  P.PHOTO_CAPTION,
  P.PHOTO_CREATED_TIME,
  P.PHOTO_MODIFIED
FROM PHOTOS P, ALBUMS A;

CREATE VIEW VIEW_EVENT_INFORMATION
AS SELECT EVENT_ID,
  EVENT_CREATOR_ID,
  EVENT_NAME,
  EVENT_TAGLINE,
  EVENT_DESCRIPTION,
  EVENT_HOST,
  EVENT_TYPE,
  EVENT_SUBTYPE,
  EVENT_ADDRESS,
  EVENT_CITY_ID,
  EVENT_START_TIME,
  EVENT_END_TIME
FROM USER_EVENTS;

CREATE VIEW VIEW_TAG_INFORMATION
AS SELECT TAG_PHOTO_ID,
  TAG_SUBJECT_ID,
  TAG_CREATED_TIME,
  TAG_X,
  TAG_Y
FROM TAGS;
