CREATE VIEW VIEW_USER_INFORMATION(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, CURRENT_CITY,
				  CURRENT_STATE, CURRENT_COUNTRY, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, INSTITUTION,
				  PROGRAM_YEAR, CONCENTRATION, DEGREE)
AS SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER,
(SELECT CITY_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (CC.CITY_ID = C.CITY_ID)
) AS CURRENT_CITY,
(SELECT STATE_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (CC.CITY_ID = C.CITY_ID)
) AS CURRENT_STATE,
(SELECT COUNTRY_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (CC.CITY_ID = C.CITY_ID)
) AS CURRENT_COUNTRY,
(SELECT CITY_NAME
	FROM CITIES
	WHERE (U.USER_ID = HC.USER_ID) AND (HC.CITY_ID = C.CITY_ID)
) AS HOMETOWN_CITY,
(SELECT STATE_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (HC.CITY_ID = C.CITY_ID)
) AS HOMETOWN_STATE,
(SELECT COUNTRY_NAME
	FROM CITIES
	WHERE (U.USER_ID = CC.USER_ID) AND (HC.CITY_ID = C.CITY_ID)
) AS HOMETOWN_COUNTRY,
E.INSTITUTION, E.PROGRAM_YEAR, P.CONCENTRATION, P.DEGREE
FROM USERS U, CITIES C, USER_CURRENT_CITIES CC, USER_HOMETOWN_CITIES HC, PROGRAMS P, EDUCATION E
WHERE (E.USER_ID = U.USER_ID) AND (P.PROGRAM_ID = E.PROGRAM_ID);

CREATE VIEW VIEW_ARE_FRIENDS (USER1_ID, USER2_ID)
AS SELECT USER1_ID, USER2_ID
FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION (ALBUM_ID, ALBUM_OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME,
				    ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, 
				    PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK)
AS SELECT A.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM PHOTOS P, ALBUMS A;
WHERE P.ALBUM_ID = A.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION (EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION,
				    EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, CITY_NAME, STATE_NAME, 
				    COUNTRY_NAME, EVENT_START_TIME, EVENT_END_TIME)
AS SELECT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, E.EVENT_START_TIME, E.EVENT_END_TIME
FROM USER_EVENTS E, CITIES C
WHERE C.CITY_ID = E.CITY_ID;

CREATE VIEW VIEW_TAG_INFORMATION (TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y)
AS SELECT TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y
FROM TAGS;
