DROP TRIGGER TR_CITIES;
DROP SEQUENCE SEQ_CITIES;

DROP TRIGGER TR_PROGRAMS;
DROP SEQUENCE SEQ_PROGRAMS;

DROP TRIGGER order_friends_pairs;

ALTER TABLE PHOTOS 
DROP CONSTRAINT CIRCULAR_PHOTOS;

DROP TABLE USER_CURRENT_CITIES;
DROP TABLE USER_HOMETOWN_CITIES;
DROP TABLE MESSAGES;
DROP TABLE EDUCATION;
DROP TABLE PROGRAMS;
DROP TABLE PARTICIPANTS;
DROP TABLE USER_EVENTS;
DROP TABLE TAGS;
DROP TABLE ALBUMS;
DROP TABLE PHOTOS;
DROP TABLE CITIES;
DROP TABLE FRIENDS;
DROP TABLE USERS;